### PR TITLE
High Availability setup

### PR DESCRIPTION
**Pull request by AnatomicJC**
Hi,

Following #19 Here is a PR for High Availability setup.

Dependencies charts (Galera, Redis, etc.) can be retrieved with `helm dep build .` command but I can restore the *.tgz files in charts sub-folders behavior if needed.

* Increased Chart apiVersion from v1 to v2
* PHP settings added based on passbolt customers feedbacks (php timeout increased, post_max_size, php-fpm pm.max_children, etc.
* Removed Avatar persistence setting as passbolt avatars are now stored in database
* renamed /etc/php/7.4/fpm/conf.d/passbolt.ini to /etc/php/7.4/fpm/pool.d/zzz-passbolt.conf as it is a php-fpm conf file and not an ini file.
* Added generate-secrets.sh script for easier GPG/JWT files creation.

At least 3 worker nodes (you can loose one) are needed to have a real HA setup.

### CODE REVIEW

**Comment by claudio-walser** [comment]
Awesome, thank you for your effort, very much appreciated.

We will check it out and test our own installation with HA as soon as possible.

**Comment by AnatomicJC** [comment]
Hi :wave: 

Did you have time to have a look and spin a passbolt setup in HA mode ?

Best,

**Comment by claudio-walser** [comment]
Not yet, we are working on it. Story is in the current sprint.
Sorry for the delay

**Comment by AnatomicJC** [comment]
Cool thanks 👍

**Comment by michizubi-SRF** [comment]
Hey @AnatomicJC 

We tested the HA setup on our environment and it worked fine, great work!
However, we decided to use the single node version for our environment. I therefore made some changes to the values.yaml so that we can continue to use this deployment without further adjustments.

I merged your PR with my changes. Please update your branch with the master.

Thanks a lot for your contribution!

**Pull request merged**
