### PR TITLE
pvc metadata name

### PR DESCRIPTION
**Pull request by ryanhagen**
keep name consistent with where its being referenced in deployment.yaml

### CODE REVIEW

**Comment by claudio-walser** [comment]
Hi Ryan, thank you very much for your contribution, nice to see people actually using it.
May you explain the current issue your code is trying to fix?

If you experience any kind of naming inconsistency, you can always pass fullnameOverride for example
https://github.com/mmz-srf/passbolt-helm#general

**Comment by ryanhagen** [comment]
I did not know about the overrides. The first time i deployed this chart it didn't work, the deployment couldn't find the pvc.

Its a bit confusing that you would need to pass in overrides to get a resource on your release to line up with how its called out in the deployment yaml. I think of an override as being something optional, not something that's required to get the release to deploy correctly.

My PR is one solution, since i now know about the override, its probably better to change the callout of the pvc in the deployment yaml to: name: {{ include "passbolt-helm.fullname" . }}-data. But ill leave that to you.

**Comment by claudio-walser** [comment]
You are right, thank you for pointing this out.
We discussed it and would prefer using passbolt-helm.fullname in the deployment as well.
Do you want to adapt your pr to this or should we fix it ourself? I would open a new PR then and closing yours.

Would you agree to test if it fixes your problem if we open a new pull request?

**Comment by mms-gianni** [comment]
I opened a pullrequest to address this Problem. 

https://github.com/mmz-srf/passbolt-helm/pull/7

**Pull request closed without merging**
